### ISSUE TITLE
'Developers' menu item is not clickable in a mobile view in iOS

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cow-web#27]
1. Open the app in a mobile view in iOS
2. Open burger menu
3. Press on the 'Developers' menu item

**AR**: nothing happens

**ER**: the menu should be closed (?) and a user should be navigated to 'Developers' part on the page

**Comment by fairlighteth** [comment]
The issues was, the main menu not 'closing' when clicking on the menu item. Fixed in #36
