### ISSUE TITLE
Add a period before 'View analytics' link

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cow-web#31]
Add a period before 'View analytics' link
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/2f130d4c-5d1f-4e27-877c-8d4bdae4e4ac)

like is it implemented in another section before 'Read more' link
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/48c7b10d-5b3b-4517-9bdd-5615956c343e)

**Comment by fairlighteth** [comment]
Fixed in https://github.com/gnosis/cow-web/pull/51
