### ISSUE TITLE
'View analytics' navigates to the top of the page

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cow-web#32]
'View analytics' link navigates to the top of the page.
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/2eeb973e-fce3-483a-b31b-b50922150d66)

May be we could navigate to https://dune.xyz/gnosis.protocol/Gnosis-Protocol-V2 ?

**Comment by fairlighteth** [comment]
Fixed in #51
