### ISSUE TITLE
Remove a glove from the Cow protocol logo in Footer on a mouse hover

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cow-web#35]
When hover a mouse on the Cow protocol logo in the Footer, a glove appears like a hovered effect. 
However, nothing happens when click on the logo. 
![image](https://user-images.githubusercontent.com/70885163/148926595-f9fd4406-c5fe-45af-82db-4f0c3bb798bd.png)

So it would be nice to remove a glove effect from the Cow protocol logo in Footer on a mouse hover
OR
make it clickable and navigate a user to the top of the page

**Comment by fairlighteth** [comment]
Fixed in #37
