### ISSUE TITLE
Poor phrasing in http "Get a price quote" example

### ISSUE THREAD

**Issue by harisang** [gnosis/cow-web#50]
The beginning of the sentence looks sloppy  "`Example, how to get.....`"

![image](https://user-images.githubusercontent.com/64154020/149150938-0fcde8c2-1de7-468d-b85b-f16c6f01b976.png)

**Comment by fairlighteth** [comment]
Agreed. Should we say:

> In this example we retrieve a price and fee quote for selling 10 WETH to buy USDC.

**Comment by harisang** [comment]
> Agreed. Should we say:
> 
> > In this example we retrieve a price and fee quote for selling 10 WETH to buy USDC.

Yes, that looks good!

**Comment by fairlighteth** [comment]
Made it slightly shorter in this PR -> https://github.com/gnosis/cow-web/pull/62
